# Generated by Django 6.1.1 on 2026-09-29 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('EXCAVADORA', 'Excavadora'), ('GENERADOR', 'Generador'), ('ANDAMIO', 'Andamio'), ('HORMIGONERA', 'Hormigonera')], max_length=30)),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('garantia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarroArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PAGADO', 'Pagado'), ('ENTREGADO', 'Entregado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PAGADO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('garantia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='renting.contratoarriendo')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_contrato', to='renting.maquinaria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='renting.carroarriendo')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_carro', to='renting.maquinaria')),
            ],
        ),
    ]
